version: '3.9'

services:
  sell-car-postgres:
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: buySellCars
    volumes:
      - buySellCars:/var/lib/postgresql/buySellCars

  buy-sell-car-redis:
    image: redis
    container_name: buySellCar-redis
    ports:
      - '6379:6379'
    restart: unless-stopped


volumes:
  buySellCars:
  buy-sell-car-redis:
